baseurl = "https://fuckcloudnative.io"
languageCode = "en-us"
DefaultContentLanguage = "zh"
title = "äº‘åŸç”Ÿå®éªŒå®¤"
theme = ["hugo-notice", "beautifulhugo"]
metaDataFormat = "yaml"
# ç»Ÿè®¡ä¸­æ–‡å­—æ•°
hasCJKLanguage = true
# æŠŠ url ä¸­çš„å¤§å†™å­—ç¬¦è½¬ä¸ºå°å†™
disablePathToLower = false
# æŠŠåˆ†ç±»ï¼ˆcategoriesï¼‰åç§°è½¬ä¸ºå°å†™
preserveTaxonomyNames = false
# å–æ¶ˆé»˜è®¤çš„ä»£ç é«˜äº®ï¼Œæˆ‘ä»¬ä½¿ç”¨prismä»£ç é«˜äº®
pygmentsUseClasses = false
# åˆ†é¡µ
Paginate = 4
# å¯ç”¨ Emoji; see emoji-cheat-sheet.com
enableEmoji = true
# åˆ›å»ºrobots.txt
enableRobotsTXT = true
googleAnalytics = "UA-145022311-1"
#pygmentCodeFences = false 
#pygmentsCodefencesGuessSyntax = false
#disqusShortname = 'fuckcloudnative'

[Blackfriday]
  # æ˜¯å¦åœ¨æ–°æ ‡ç­¾é¡µæ‰“å¼€é“¾æ¥
  hrefTargetBlank = true

[Params]
  homeTitle = "Hi,æˆ‘æ˜¯ç±³å¼€æœ—åŸºæ¨" # Set a different text for the header on the home page
  titleicon = '<i class="fab fa-redhat"></i>'
  subtitle = "æˆ‘å¯ä»¥ç»™ä½ æä¾›äº‘åŸç”Ÿæ–¹é¢çš„çŸ¥è¯†ä»¥åŠå¸®åŠ©ä½ æé«˜èµ„æºæ•´åˆèƒ½åŠ›"
  keywords = "dockerã€kubernetesã€istioã€devopsã€prometheusã€envoyã€corednsã€hugoã€golangã€äº‘åŸç”Ÿã€å¾®æœåŠ¡"
  description = "äº‘åŸç”Ÿå®éªŒå®¤æ˜¯ä¸€ä¸ªå…³æ³¨å®¹å™¨ã€kubernetesã€istioã€devopsã€prometheusã€envoyã€golangã€äº‘åŸç”Ÿã€å¾®æœåŠ¡ç­‰æŠ€æœ¯çš„ä¸ªäººåšå®¢ã€‚"
  mainSections = ["posts"]
  logo = "https://hugo-picture.oss-cn-beijing.aliyuncs.com/blog/2019-08-26-WechatIMG12268.jpeg" # Expecting square dimensions
  favicon = "https://hugo-picture.oss-cn-beijing.aliyuncs.com/favicon-32x32.png"
  dateFormat = "2006 å¹´ 1 æœˆ 2 æ—¥"
  commit = false
  rss = true
  comments = true 
  readingTime = true
  wordCount = true
  useHLJS = false
  selfHosted = true 
  socialShare = true
  #delayDisqus = true
  showRelatedPosts = true
  # busuanzi
  busuanzi = true
  busuanzi_site_offset = 100000 
  reward = true
  customCSSAssets = ["fontawesome/css/all.css", "css/fonts.css", "css/fonts-zh.css", "css/prism.css", "css/toc.css", "css/pace.css", "css/search.css"]
  customJSAssets = ["js/prism.js", "js/prism-copy-to-clipboard.min.js", "js/prism-match-braces.min.js", "js/photoswipe.min.js", "js/photoswipe-ui-default.min.js", "js/jquery.lazyload.min.js", "js/instant.page.min.js"]
  algolia = "62fd06bd949abb4211bfab0aa288f67b" # API key
#  hideAuthor = true
  # gcse = "014738201351737010393:0qb0mkrjow4" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

[[Params.bigimg]]
src = "https://hugo-picture.oss-cn-beijing.aliyuncs.com/images/2qx3wkj.jpeg"
desc = "Long Live Containers"

[[Params.bigimg]]
src = "https://hugo-picture.oss-cn-beijing.aliyuncs.com/images/kw1s3z8z.jpeg"
desc = "Long Live Kubernetes"

[[Params.bigimg]]
src = "https://hugo-picture.oss-cn-beijing.aliyuncs.com/images/envoy_proxy.png"
desc = "Long Live Envoy Proxy"

[[Params.bigimg]]
src = "https://hugo-picture.oss-cn-beijing.aliyuncs.com/images/istio-1280x595.jpg"
desc = "Long Live Istio"

[[Params.bigimg]]
src = "https://hugo-picture.oss-cn-beijing.aliyuncs.com/images/service-mesh.jpeg"
desc = "Long Live Service Mesh"
#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "ç±³å¼€æœ—åŸºæ¨"
  website = "https://fuckcloudnative.io"
  weixin = "https://hugo-picture.oss-cn-beijing.aliyuncs.com/blog/2019-06-13-%E9%BB%98%E8%AE%A4%E6%A0%87%E9%A2%98_%E6%A8%AA%E7%89%88%E4%BA%8C%E7%BB%B4%E7%A0%81_2019.05.17.1.1.png"
  weibo = "3496206342"
  email = "yangchuansheng33@gmail.com"
  #facebook = "username"
  github = "yangchuansheng"
  gdrive = "0By_W-zIhlMXqSGJyU3pHaVVpV2M"
  #gitlab = "username"
  #bitbucket = "username"
  twitter = "RyangYang1"
  #reddit = "username"
  linkedin = "yang-ryan-b6659b106"
  #xing = "username"
  #stackoverflow = "users/XXXXXXX/username"
  #snapchat = "username"
  #instagram = "username"
  #youtube = "user/username" # or channel/channelname
  #soundcloud = "username"
  #spotify = "username"
  #bandcamp = "username"
  #itchio = "username"
  #vk = "username"
  #paypal = "username"
  #telegram = "username"
  #500px = "username"
  #codepen = "username"
  #mastodon = "url"
  #kaggle = "username"
  #weibo = "username"
  #slack = "username"

[[menu.main]]
    identifier = "Categories"
    pre = '<i class="fas fa-dharmachakra fa-spin" style="color:#986dbd"></i>'
    name = "æ–‡ç« åˆ†ç±»"
    weight = 1

[[menu.main]]
    parent = "Categories"
    name = "kubernetes"
    url = "categories/kubernetes/"
    weight = 1

[[menu.main]]
    parent = "Categories"
    name = "ç›‘æ§"
    url = "categories/monitoring/"
    weight = 2

[[menu.main]]
    parent = "Categories"
    name = "Service Mesh"
    url = "categories/service-mesh/"
    weight = 3

[[menu.main]]
    parent = "Categories"
    name = "DevOps"
    url = "categories/devops/"
    weight = 4

[[menu.main]]
    parent = "Categories"
    name = "Docker"
    url = "categories/docker/"
    weight = 5

[[menu.main]]
    parent = "Categories"
    name = "Linux"
    url = "categories/linux/"
    weight = 7

[[menu.main]]
    parent = "Categories"
    name = "Python"
    url = "categories/python/"
    weight = 9

[[menu.main]]
    parent = "Categories"
    name = "ç½‘ç»œ"
    url = "categories/network/"
    weight = 11

[[menu.main]]
    parent = "Categories"
    name = " è´Ÿè½½å‡è¡¡"
    url = "categories/loadbalance/"
    weight = 13

[[menu.main]]
    parent = "Categories"
    name = "ç§‘å­¦ä¸Šç½‘"
    url = "categories/gfw/"
    weight = 15

[[menu.main]]
    parent = "Categories"
    name = "æ•°å­¦"
    url = "categories/math/"
    weight = 17

[[menu.main]]
    parent = "Categories"
    name = "é»‘ç§‘æŠ€"
    url = "categories/share/"
    weight = 19

[[menu.main]]
    parent = "Categories"
    name = "Hugo"
    url = "categories/hugo/"
    weight = 21

[[menu.main]]
    identifier = "Books"
    pre = '<i class="fab fa-docker"></i>'
    name = "ç”µå­ä¹¦"
    weight = 2

[[menu.main]]
    parent = "Books"
    name = "Prometheus ä¸­æ–‡æ–‡æ¡£"
    url = "prometheus-handbook/"
    weight = 1

[[menu.main]]
    parent = "Books"
    name = "å¤©æ‰æºè‡ªåˆ»æ„ç»ƒä¹ "
    url = "talent-is-overrated/"
    weight = 2

[[menu.main]]
    parent = "Books"
    name = "Docker handbook"
    url = "https://www.gitbook.com/book/yeasy/docker_practice"
    weight = 7

[[menu.main]]
    parent = "Books"
    name = "Istio service mesh"
    url = "https://istio.io/zh/docs"
    weight = 6

[[menu.main]]
    parent = "Books"
    name = "é˜®ä¸€å³°ä¹¦å•"
    url = "https://github.com/ruanyf/reading-list"
    weight = 5

[[menu.main]]
    parent = "Books"
    name = "æœºå™¨å­¦ä¹ ç¬”è®°"
    url = "https://github.com/fengdu78/Coursera-ML-AndrewNg-Notes"
    weight = 4

[[menu.main]]
    parent = "Books"
    name = "Go å…¥é—¨æŒ‡å—"
    url = "the-way-to-go/"
    weight = 3

[[menu.main]]
    identifier = "Cheats"
    pre = '<i class="fas fa-book"></i>'
    name = "è‘µèŠ±å®å…¸"
    weight = 4

[[menu.main]]
    parent = "Cheats"
    name = " è‹±è¯­å­¦ä¹ ç»ˆæç§˜è¯€"
    url = "learn-english/"
    weight = 2

[[menu.main]]
    parent = "Cheats"
    name = "A Day in the life of Jeff"
    url = "a-day-in-the-life-of-jeff/"
    weight = 3

[[menu.main]]
    identifier = "Welfare"
    name = "ğŸ˜±ç¦åˆ©"
    weight = 5

[[menu.main]]
    parent = "Welfare"
    name = "äº‘åŸç”Ÿå¯¼èˆª"
    url = "https://nav.fuckcloudnative.io"
    weight = 1

[[menu.main]]
    parent = "Welfare"
    name = "è°·æ­Œæœç´¢"
    url = "https://google.fuckcloudnative.io"
    weight = 2

[[menu.main]]
    parent = "Welfare"
    name = "ç§å­æœç´¢"
    url = "https://bt.fuckcloudnative.io"
    weight = 3

[[menu.main]]
    identifier = "Rss"
    name = "Rss è®¢é˜…"
    url = "index.xml"
    weight = 6
